### ISSUE TITLE
iOS 10.3.1 证书安装成功后，依然提示无法连接到

### ISSUE THREAD

**Issue by pandaApe** [zhao0/ipapk-server#10]
如题。

但是在iOS9.3和iOS8上就是正常的。请问是什么原因？

**Comment by zhao0** [comment]
之前是好的吗？我也是10.3.1，正常使用

**Comment by pandaApe** [comment]
ipapk-server 的代码我没动过啊。iOS10.3之前是正常的，前几天手机系统做了升级，升级后不行了。真机，模拟器都是一样的情况。

**Comment by SimleCp** [comment]
我的10.3.1也是一样的. 证书安装成功了, 但是点击下载还是一样的说无法连接到xxxx

**Comment by pandaApe** [comment]
找到一个变通的方法：
> On iOS 10.3:

> Settings > General > About (logically...) > Certificate Trust Settings > Enable Full Trust for Root Certificates

参考：
[https://forums.developer.apple.com/message/212408#212408](https://forums.developer.apple.com/message/212408#212408)

[https://forums.developer.apple.com/thread/71789](https://forums.developer.apple.com/thread/71789)

**Comment by SimleCp** [comment]
@pandaApe 很nice. 确实能用了.

**Comment by SimleCp** [comment]
@zhao0 能否增加移除历史APP和编辑APP提交描述的接口?

**Comment by pandaApe** [comment]
自己写吧。在大神的接口上修改。 @SimleCp

**Comment by zhao0** [comment]
@SimleCp 有计划，如果你有余力开发，欢迎提MR

**Comment by SimleCp** [comment]
@zhao0 @pandaApe 我能说我不会node.js么....而且最近很忙 没空学这个...

**Comment by pandaApe** [comment]
@SimleCp 我在大神的基础上增加了测试和线上环境的区分。公司产品比较多，又增加了一个查询所有产品的接口。优化起来还挺好用的。

**Comment by SimleCp** [comment]
@pandaApe 期待你的 Pull requests ^-^ 让我们也能用上

**Comment by pandaApe** [comment]
哈哈，好的啊。
