### ISSUE TITLE
Ubuntu 14.04上报EXDEV 重命名apk文件名报错

### ISSUE THREAD

**Issue by songzcn** [zhao0/ipapk-server#12]
{"error":{"errno":-18,"code":"EXDEV","syscall":"rename","path":"/tmp/dyXE5JGusg4UcNGGd6_IGVy6.apk","dest":"/home/hp/.ipapk-server/apk/1ea77120-d8e1-4fb3-bdca-8a1f411a5a6a.apk"}}

**Comment by zhao0** [comment]
你的机器是不是有多个分区？
参考这篇回答 [https://stackoverflow.com/questions/21071303/node-js-exdev-rename-error](node-js-exdev-rename-error)

**Comment by songzcn** [comment]
嗯是的，fs.rename的坑。。昨天改掉了
