### ISSUE TITLE
获取ipa应用名称时建议对CFBundleDisplayName做下兼容

### ISSUE THREAD

**Issue by lyzz0612** [zhao0/ipapk-server#21]
https://github.com/zhao0/ipapk-server/blob/746d0e208be7c25773dab63d8dcb004a4fa760c7/ipapk-server.js#L308
我们打包出来的应用info.plist只配置CFBundleDisplayName，没有CFBundleName，导致脚本获取到的名字为空。感觉应该有不少人是一样的情况，希望能做下兼容。

**Comment by zhao0** [comment]
有些是通过国际化配置CFBundleDisplayName的，plist配置为空，
