### ISSUE TITLE
运行到这一步的时候卡着不动了，是我环境的问题吗

### ISSUE THREAD

**Issue by CallMonster** [zhao0/ipapk-server#22]
EACCES attempting to reinstall using temporary dev dir "/root/node-v8.11.2-linux-x86/lib/node_modules/ipapk-server/node_modules/sqlite3/.node-gyp"

**Comment by zhao0** [comment]
国内可能无法访问S3，使用淘宝镜像下载预编译的sqlite3（Ubuntu下镜像无效）
```
$ npm install -g ipapk-server --node_sqlite3_binary_host_mirror=https://npm.taobao.org/mirrors
```
