### ISSUE TITLE
iOS无法下载，Android包无法上传

### ISSUE THREAD

**Issue by liuxiaoxin369** [zhao0/ipapk-server#29]
the iOS's package can't download 
![bbdc9d4ad968e099b57a53400c2d0922](https://user-images.githubusercontent.com/20962818/43043486-7123ae8c-8dc7-11e8-8371-528a7a914960.jpg)

the android's package can't upload 
![9063451d5f03761a558473bf235d2381](https://user-images.githubusercontent.com/20962818/43043451-b9531aea-8dc6-11e8-98e2-bd6bcd13d7da.jpg)

**Comment by QQQAA** [comment]
建议参考下 官方文档  console打印你的数据 尝试更新aapt-linux&aapt-osx并改用stream流的方式解析文件
https://nodejs.org/api/buffer.html#buffer_buffer_kmaxlength
