### ISSUE TITLE
安卓上传不同版本apk会覆盖server上版本且上传成功后页面上文件名最后会显示build No

### ISSUE THREAD

**Issue by songzcn** [zhao0/ipapk-server#3]

**Comment by songzcn** [comment]
![image](https://cloud.githubusercontent.com/assets/16219925/21759303/4ef8f058-d67e-11e6-98e8-487a29e149b6.png)
如图所示

**Comment by songzcn** [comment]
并且name显示换行了

**Comment by zhao0** [comment]
能提供更详细的信息吗

**Comment by zhao0** [comment]
你点一下那一行是可以展开显示更多版本的

**Comment by songzcn** [comment]
刚才点了加载更多没有别的版本，现在有了。。。
