### ISSUE TITLE
extract ipa png icon failed

### ISSUE THREAD

**Issue by red3** [zhao0/ipapk-server#6]
处理 icon 的时候报错：
> /Users/herui/.ipapk-server/icon/46bf9893-685e-40d0-bbcf-8826e57fc867.png : not an -iphone crushed PNG file

应该是  extractIpaIcon 这个函数里面 `fs.writeFile`报的错。

我的尝试：
1. 确保 icon 是 png，同时试了上传微信的 ipa 包还是报这个错误
2. ios-ipa-server 项目是可以成功显示图片的，我看了下，他用的是 `fs.writeFileSync`，但是也会有报警：libpng warning: Input PNG is not optimized for iPhone OS.  Copying source file to destination...

还是说我的 libpng 版本有问题？

**Comment by zhao0** [comment]
普通情况下ipa里面的png图片会经过pngcrush压缩，报错是这个图片没有经过pngcrush压缩，我今天加个处理，没有压缩过就直接解压

**Comment by zhao0** [comment]
不一定是

**Comment by red3** [comment]
我查了下，找到这个链接：https://discussions.apple.com/thread/7263918?start=0&tstart=0

可能是这样：
用 xcassets 管理 appicon 后，xcassets 里面 png 文件不会被压缩了吧

**Comment by zhao0** [comment]
这个我不太清楚，我要兼容两种

**Comment by red3** [comment]
好的

**Comment by zhao0** [comment]
我更新到0.2.4了，你试一下

**Comment by red3** [comment]
👍 可以了，关闭这个 issue 吧

**Comment by zhao0** [comment]
感谢反馈，比心
